# Generated by Django 5.1.5 on 2025-01-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0005_alter_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.ImageField(null=True, upload_to='posts/images'),
        ),
    ]
